using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Entities.Configuration;
using Entities.Enums;
using Entities.Inventory;
using Entities.Kitchen;
using Entities.Masters;
using Entities.Organisation;
using Entities.Reports;
using Entities.Sales;
using Entities.Integration;
using Entities.Audit;
using Data.Persistence;

namespace Data.Seeding;

public static class DbSeeder
{
    public static async Task SeedAsync(AppDbContext db, UserManager<IdentityUser<int>> userManager, RoleManager<IdentityRole<int>> roleManager)
    {
        var roles = new[] { "Admin", "Manager", "Cashier", "Captain", "Kitchen", "StockManager", "Accountant" };
        foreach (var role in roles)
        {
            if (!await roleManager.RoleExistsAsync(role))
            {
                await roleManager.CreateAsync(new IdentityRole<int>(role));
            }
        }

        if (!db.Outlets.Any())
        {
            db.Outlets.Add(new Outlet
            {
                TenantId = 1,
                OutletName = "Default Outlet",
                StateCode = "27",
                FssaiNumber = "12345678901234"
            });
            await db.SaveChangesAsync();
        }

        const int outletId = 1;
        if (!db.Outlets.Any(x => x.OutletId == outletId))
        {
            if (!db.Outlets.Any())
            {
                db.Outlets.Add(new Outlet
                {
                    TenantId = 1,
                    OutletName = "Default Outlet",
                    StateCode = "27",
                    FssaiNumber = "12345678901234"
                });
                await db.SaveChangesAsync();
            }
        }

        if (!db.TaxConfigurations.Any())
        {
            db.TaxConfigurations.Add(new TaxConfiguration
            {
                OutletId = outletId,
                ScenarioType = "Standalone",
                TotalGstPercent = 5m,
                CgstPercent = 2.5m,
                SgstPercent = 2.5m,
                IgstPercent = 0m,
                IsItcAllowed = false,
                EffectiveFrom = new DateTime(2025, 9, 22)
            });
        }

        if (!db.NumberSeries.Any())
        {
            db.NumberSeries.AddRange(
                new NumberSeries { OutletId = outletId, SeriesKey = Entities.Enums.NumberSeriesKey.Bill, Prefix = "TI", NumberLength = 6 },
                new NumberSeries { OutletId = outletId, SeriesKey = Entities.Enums.NumberSeriesKey.Quote, Prefix = "QT", NumberLength = 5 },
                new NumberSeries { OutletId = outletId, SeriesKey = Entities.Enums.NumberSeriesKey.KOT, Prefix = "KOT", NumberLength = 5 });
        }

        if (!db.RestaurantSettings.Any())
        {
            db.RestaurantSettings.AddRange(
                new RestaurantSetting { OutletId = outletId, SettingKey = "RestaurantName", SettingValue = "Restaurant" },
                new RestaurantSetting { OutletId = outletId, SettingKey = "FssaiNumber", SettingValue = "12345678901234" },
                new RestaurantSetting { OutletId = outletId, SettingKey = "ServiceChargeDefault", SettingValue = "0" },
                new RestaurantSetting { OutletId = outletId, SettingKey = "ManagerPin", SettingValue = "9876" },
                new RestaurantSetting { OutletId = outletId, SettingKey = "BillTemplateName", SettingValue = "Classic GST A4" },
                new RestaurantSetting { OutletId = outletId, SettingKey = "BillTemplateHeader", SettingValue = "Thank you for dining with us" },
                new RestaurantSetting { OutletId = outletId, SettingKey = "BillTemplateFooter", SettingValue = "Visit Again | GST invoice generated by system" },
                new RestaurantSetting { OutletId = outletId, SettingKey = "BillTemplateTerms", SettingValue = "All disputes subject to local jurisdiction." },
                new RestaurantSetting { OutletId = outletId, SettingKey = "MenuImageBasePath", SettingValue = "/images/menu" });
        }

        var requiredCategories = new[]
        {
            ("Starters", 1, true),
            ("Main Course", 2, true),
            ("Breads", 3, true),
            ("Desserts", 4, true),
            ("Beverages", 5, true),
        };
        foreach (var (name, sort, isActive) in requiredCategories)
        {
            if (!db.Categories.Any(x => x.OutletId == outletId && x.CategoryName == name))
            {
                db.Categories.Add(new Category
                {
                    OutletId = outletId,
                    CategoryName = name,
                    SortOrder = sort,
                    IsActive = isActive,
                    IsDeleted = false
                });
            }
        }

        if (!db.Units.Any())
        {
            db.Units.AddRange(
                new Unit { OutletId = outletId, UnitName = "Nos", UnitCode = "NOS" },
                new Unit { OutletId = outletId, UnitName = "Kg", UnitCode = "KG" },
                new Unit { OutletId = outletId, UnitName = "Litre", UnitCode = "LTR" });
        }

        if (!db.DiningTables.Any())
        {
            db.DiningTables.AddRange(
                new DiningTables { OutletId = outletId, TableName = "Ground-1", Area = "Ground", Capacity = 4 },
                new DiningTables { OutletId = outletId, TableName = "Ground-2", Area = "Ground", Capacity = 6 },
                new DiningTables { OutletId = outletId, TableName = "AC-1", Area = "AC", Capacity = 2 },
                new DiningTables { OutletId = outletId, TableName = "AC-2", Area = "AC", Capacity = 4 },
                new DiningTables { OutletId = outletId, TableName = "NonAC-1", Area = "Non-AC", Capacity = 4 },
                new DiningTables { OutletId = outletId, TableName = "NonAC-2", Area = "Non-AC", Capacity = 8 },
                new DiningTables { OutletId = outletId, TableName = "Outdoor-1", Area = "Outdoor", Capacity = 2 },
                new DiningTables { OutletId = outletId, TableName = "Outdoor-2", Area = "Outdoor", Capacity = 6 });
        }

        if (!db.KitchenStations.Any())
        {
            db.KitchenStations.AddRange(
                new KitchenStation { OutletId = outletId, StationName = "Main Kitchen", SortOrder = 1 },
                new KitchenStation { OutletId = outletId, StationName = "Beverage", SortOrder = 2 });
        }

        // Flush newly inserted categories before item dictionary lookup.
        await db.SaveChangesAsync();

        if (!db.Items.Any())
        {
            var categories = db.Categories
                .Where(x => x.OutletId == outletId)
                .ToDictionary(x => x.CategoryName, x => x.CategoryId);

            // Safety net for partially seeded databases.
            var missing = new[] { "Starters", "Main Course", "Breads", "Desserts", "Beverages" }
                .Where(x => !categories.ContainsKey(x))
                .ToList();
            if (missing.Count > 0)
            {
                var nextSort = db.Categories.Where(x => x.OutletId == outletId).Select(x => x.SortOrder).DefaultIfEmpty(0).Max();
                foreach (var name in missing)
                {
                    nextSort++;
                    db.Categories.Add(new Category { OutletId = outletId, CategoryName = name, SortOrder = nextSort });
                }
                await db.SaveChangesAsync();
                categories = db.Categories
                    .Where(x => x.OutletId == outletId)
                    .ToDictionary(x => x.CategoryName, x => x.CategoryId);
            }

            db.Items.AddRange(
                new Item
                {
                    OutletId = outletId,
                    CategoryId = categories["Starters"],
                    ItemCode = "STR001",
                    ItemName = "Paneer Tikka",
                    SalePrice = 260m,
                    GstPercent = 5m,
                    IsTaxInclusive = false,
                    TaxType = TaxType.GST
                },
                new Item
                {
                    OutletId = outletId,
                    CategoryId = categories["Main Course"],
                    ItemCode = "MNC001",
                    ItemName = "Veg Biryani",
                    SalePrice = 220m,
                    GstPercent = 5m,
                    IsTaxInclusive = false,
                    TaxType = TaxType.GST
                },
                new Item
                {
                    OutletId = outletId,
                    CategoryId = categories["Breads"],
                    ItemCode = "BRD001",
                    ItemName = "Butter Naan",
                    SalePrice = 45m,
                    GstPercent = 5m,
                    IsTaxInclusive = false,
                    TaxType = TaxType.GST
                },
                new Item
                {
                    OutletId = outletId,
                    CategoryId = categories["Desserts"],
                    ItemCode = "DST001",
                    ItemName = "Gulab Jamun",
                    SalePrice = 90m,
                    GstPercent = 5m,
                    IsTaxInclusive = false,
                    TaxType = TaxType.GST
                },
                new Item
                {
                    OutletId = outletId,
                    CategoryId = categories["Beverages"],
                    ItemCode = "BEV001",
                    ItemName = "Masala Chai",
                    SalePrice = 35m,
                    GstPercent = 5m,
                    IsTaxInclusive = false,
                    TaxType = TaxType.GST
                });
            await db.SaveChangesAsync();
        }

        var defaultCategories = db.Categories
            .Where(x => x.OutletId == outletId)
            .ToDictionary(x => x.CategoryName, x => x.CategoryId);
        var additionalVegItems = new[]
        {
            new { Category = "Starters", Code = "STR002", Name = "Hara Bhara Kebab", Sale = 240m },
            new { Category = "Starters", Code = "STR003", Name = "Veg Spring Roll", Sale = 180m },
            new { Category = "Starters", Code = "STR004", Name = "Crispy Corn", Sale = 170m },
            new { Category = "Starters", Code = "STR005", Name = "Gobi Manchurian", Sale = 190m },
            new { Category = "Starters", Code = "STR006", Name = "Veg Manchurian Dry", Sale = 210m },
            new { Category = "Starters", Code = "STR007", Name = "Cheese Corn Balls", Sale = 220m },
            new { Category = "Starters", Code = "STR008", Name = "Paneer 65", Sale = 250m },
            new { Category = "Starters", Code = "STR009", Name = "Mushroom Pepper Fry", Sale = 230m },
            new { Category = "Starters", Code = "STR010", Name = "Corn Tikki", Sale = 175m },
            new { Category = "Starters", Code = "STR011", Name = "Baby Corn Chilli", Sale = 205m },
            new { Category = "Main Course", Code = "MNC002", Name = "Paneer Butter Masala", Sale = 280m },
            new { Category = "Main Course", Code = "MNC003", Name = "Dal Tadka", Sale = 160m },
            new { Category = "Main Course", Code = "MNC004", Name = "Kadai Paneer", Sale = 290m },
            new { Category = "Main Course", Code = "MNC005", Name = "Palak Paneer", Sale = 275m },
            new { Category = "Main Course", Code = "MNC006", Name = "Veg Kolhapuri", Sale = 230m },
            new { Category = "Main Course", Code = "MNC007", Name = "Mix Veg Curry", Sale = 210m },
            new { Category = "Main Course", Code = "MNC008", Name = "Jeera Rice", Sale = 140m },
            new { Category = "Main Course", Code = "MNC009", Name = "Steam Rice", Sale = 120m },
            new { Category = "Main Course", Code = "MNC010", Name = "Paneer Lababdar", Sale = 295m },
            new { Category = "Main Course", Code = "MNC011", Name = "Veg Pulao", Sale = 180m },
            new { Category = "Breads", Code = "BRD002", Name = "Tandoori Roti", Sale = 25m },
            new { Category = "Breads", Code = "BRD003", Name = "Garlic Naan", Sale = 60m },
            new { Category = "Breads", Code = "BRD004", Name = "Plain Naan", Sale = 40m },
            new { Category = "Breads", Code = "BRD005", Name = "Lachha Paratha", Sale = 55m },
            new { Category = "Breads", Code = "BRD006", Name = "Missi Roti", Sale = 45m },
            new { Category = "Breads", Code = "BRD007", Name = "Butter Roti", Sale = 35m },
            new { Category = "Breads", Code = "BRD008", Name = "Roomali Roti", Sale = 30m },
            new { Category = "Breads", Code = "BRD009", Name = "Stuffed Kulcha", Sale = 70m },
            new { Category = "Breads", Code = "BRD010", Name = "Ajwain Paratha", Sale = 52m },
            new { Category = "Breads", Code = "BRD011", Name = "Methi Thepla", Sale = 48m },
            new { Category = "Desserts", Code = "DST002", Name = "Rasmalai", Sale = 110m },
            new { Category = "Desserts", Code = "DST003", Name = "Kulfi", Sale = 95m },
            new { Category = "Desserts", Code = "DST004", Name = "Gajar Halwa", Sale = 130m },
            new { Category = "Desserts", Code = "DST005", Name = "Moong Dal Halwa", Sale = 140m },
            new { Category = "Desserts", Code = "DST006", Name = "Ice Cream Sundae", Sale = 125m },
            new { Category = "Desserts", Code = "DST007", Name = "Chocolate Brownie", Sale = 160m },
            new { Category = "Desserts", Code = "DST008", Name = "Caramel Custard", Sale = 115m },
            new { Category = "Desserts", Code = "DST009", Name = "Falooda", Sale = 145m },
            new { Category = "Desserts", Code = "DST010", Name = "Shahi Tukda", Sale = 135m },
            new { Category = "Desserts", Code = "DST011", Name = "Fruit Cream", Sale = 120m },
            new { Category = "Beverages", Code = "BEV002", Name = "Sweet Lassi", Sale = 70m },
            new { Category = "Beverages", Code = "BEV003", Name = "Fresh Lime Soda", Sale = 90m },
            new { Category = "Beverages", Code = "BEV004", Name = "Cold Coffee", Sale = 120m },
            new { Category = "Beverages", Code = "BEV005", Name = "Mango Shake", Sale = 130m },
            new { Category = "Beverages", Code = "BEV006", Name = "Buttermilk", Sale = 45m },
            new { Category = "Beverages", Code = "BEV007", Name = "Mint Mojito", Sale = 110m },
            new { Category = "Beverages", Code = "BEV008", Name = "Classic Lemonade", Sale = 80m },
            new { Category = "Beverages", Code = "BEV009", Name = "Watermelon Cooler", Sale = 105m },
            new { Category = "Beverages", Code = "BEV010", Name = "Iced Tea", Sale = 95m },
            new { Category = "Beverages", Code = "BEV011", Name = "Masala Soda", Sale = 75m }
        };
        foreach (var seed in additionalVegItems)
        {
            if (db.Items.Any(x => x.OutletId == outletId && x.ItemCode == seed.Code))
            {
                continue;
            }
            if (!defaultCategories.TryGetValue(seed.Category, out var categoryId))
            {
                continue;
            }
            db.Items.Add(new Item
            {
                OutletId = outletId,
                CategoryId = categoryId,
                ItemCode = seed.Code,
                ItemName = seed.Name,
                SalePrice = seed.Sale,
                GstPercent = 5m,
                IsTaxInclusive = false,
                TaxType = TaxType.GST
            });
        }

        var grocerySeedItems = new[]
        {
            new { Name = "Milk", UnitCode = "LTR" },
            new { Name = "Eggs", UnitCode = "NOS" },
            new { Name = "Bread", UnitCode = "NOS" },
            new { Name = "Butter", UnitCode = "KG" },
            new { Name = "Apples", UnitCode = "KG" },
            new { Name = "Rice", UnitCode = "KG" },
            new { Name = "Millets", UnitCode = "KG" },
            new { Name = "Pasta", UnitCode = "KG" },
            new { Name = "Chicken", UnitCode = "KG" },
            new { Name = "Beans", UnitCode = "KG" },
            new { Name = "Cooking Oil", UnitCode = "LTR" },
            new { Name = "Salt", UnitCode = "KG" },
            new { Name = "Pepper", UnitCode = "KG" },
            new { Name = "Coffee", UnitCode = "KG" },
            new { Name = "Tea", UnitCode = "KG" },
            new { Name = "Toilet Paper", UnitCode = "NOS" },
            new { Name = "Dish Soap", UnitCode = "LTR" },
            new { Name = "All-purpose Cleaner", UnitCode = "LTR" }
        };

        var groceryUnitMap = db.Units
            .Where(x => x.OutletId == outletId)
            .ToDictionary(x => x.UnitCode, x => x.UnitId);

        foreach (var grocery in grocerySeedItems)
        {
            if (!db.Groceries.Any(x => x.OutletId == outletId && x.GroceryName == grocery.Name))
            {
                db.Groceries.Add(new Grocery
                {
                    OutletId = outletId,
                    GroceryName = grocery.Name,
                    IsActive = true,
                    IsDeleted = false
                });
            }
        }

        await db.SaveChangesAsync();

        var groceryIdMap = db.Groceries
            .Where(x => x.OutletId == outletId && !x.IsDeleted)
            .ToDictionary(x => x.GroceryName, x => x.GroceryId);

        foreach (var grocery in grocerySeedItems)
        {
            if (!groceryIdMap.TryGetValue(grocery.Name, out var groceryId))
            {
                continue;
            }

            if (db.GroceryStockItems.Any(x => x.OutletId == outletId && x.GroceryId == groceryId))
            {
                continue;
            }

            groceryUnitMap.TryGetValue(grocery.UnitCode, out var unitId);
            db.GroceryStockItems.Add(new GroceryStockItem
            {
                OutletId = outletId,
                GroceryId = groceryId,
                UnitId = unitId > 0 ? unitId : null,
                CurrentQty = 0m,
                ReorderLevel = 0m,
                IsActive = true,
                IsDeleted = false
            });
        }
        await db.SaveChangesAsync();

        var menuImageSettings = new Dictionary<string, string>
        {
            ["Paneer Tikka"] = "paneer-tikka.jpg",
            ["Veg Biryani"] = "veg-biryani.jpg",
            ["Butter Naan"] = "butter-naan.jpg",
            ["Gulab Jamun"] = "gulab-jamun.jpg",
            ["Masala Chai"] = "masala-chai.jpg",
            ["Hara Bhara Kebab"] = "hara-bhara-kebab.jpg",
            ["Veg Spring Roll"] = "veg-spring-roll.jpg",
            ["Paneer Butter Masala"] = "paneer-butter-masala.jpg",
            ["Dal Tadka"] = "dal-tadka.jpg",
            ["Tandoori Roti"] = "tandoori-roti.jpg",
            ["Garlic Naan"] = "garlic-naan.jpg",
            ["Rasmalai"] = "rasmalai.jpg",
            ["Sweet Lassi"] = "sweet-lassi.jpg",
            ["Fresh Lime Soda"] = "fresh-lime-soda.jpg"
        };
        foreach (var kv in menuImageSettings)
        {
            var key = $"MenuImage:{kv.Key}";
            if (!db.RestaurantSettings.Any(x => x.OutletId == outletId && x.SettingKey == key))
            {
                db.RestaurantSettings.Add(new RestaurantSetting
                {
                    OutletId = outletId,
                    SettingKey = key,
                    SettingValue = kv.Value
                });
            }
        }

        await db.SaveChangesAsync();

        await SeedTransactionalDemoDataAsync(outletId);

        var adminUser = await userManager.FindByNameAsync("Admin")
            ?? await userManager.FindByEmailAsync("admin@restaurant.local");

        if (adminUser is null)
        {
            adminUser = new IdentityUser<int>
            {
                UserName = "Admin",
                Email = "admin@restaurant.local",
                EmailConfirmed = true
            };

            var createResult = await userManager.CreateAsync(adminUser, "Admin@123");
            if (!createResult.Succeeded)
            {
                throw new InvalidOperationException(
                    $"Failed to create default admin user: {string.Join(", ", createResult.Errors.Select(x => x.Description))}");
            }
        }
        else
        {
            adminUser.UserName = "Admin";
            adminUser.Email ??= "admin@restaurant.local";
            adminUser.EmailConfirmed = true;
            await userManager.UpdateAsync(adminUser);

            if (await userManager.HasPasswordAsync(adminUser))
            {
                var removePasswordResult = await userManager.RemovePasswordAsync(adminUser);
                if (!removePasswordResult.Succeeded)
                {
                    throw new InvalidOperationException(
                        $"Failed to reset admin password: {string.Join(", ", removePasswordResult.Errors.Select(x => x.Description))}");
                }
            }

            var addPasswordResult = await userManager.AddPasswordAsync(adminUser, "Admin@123");
            if (!addPasswordResult.Succeeded)
            {
                throw new InvalidOperationException(
                    $"Failed to set admin password: {string.Join(", ", addPasswordResult.Errors.Select(x => x.Description))}");
            }
        }

        if (!await userManager.IsInRoleAsync(adminUser, "Admin"))
        {
            await userManager.AddToRoleAsync(adminUser, "Admin");
        }

        async Task SeedTransactionalDemoDataAsync(int outletSeedId)
        {
            var bizDate = DateOnly.FromDateTime(DateTime.UtcNow.Date);
            var seedItems = db.Items.Where(x => x.OutletId == outletSeedId).OrderBy(x => x.ItemId).Take(3).ToList();
            if (seedItems.Count < 3) return;

            Bill? paidBill = null;
            if (!db.Bills.Any(x => x.OutletId == outletSeedId))
            {
                var billNo = "TI000001";
                var bill = new Bill(outletSeedId, billNo, bizDate, BillType.DineIn);
                bill.AddItem(new BillItem(seedItems[0].ItemId, seedItems[0].ItemName, 1, seedItems[0].SalePrice, 0m, 0m));
                bill.AddItem(new BillItem(seedItems[1].ItemId, seedItems[1].ItemName, 1, seedItems[1].SalePrice, 0m, 0m));
                bill.Settle([new Payment(PaymentMode.Cash, bill.GrandTotal, referenceNo: $"{billNo}-PAY")]);
                db.Bills.Add(bill);
                await db.SaveChangesAsync();
                paidBill = bill;
            }
            else
            {
                paidBill = db.Bills
                    .Where(x => x.OutletId == outletSeedId)
                    .OrderByDescending(x => x.BillId)
                    .FirstOrDefault();
            }

            if (!db.KotHeaders.Any(x => x.OutletId == outletSeedId) && paidBill is not null)
            {
                var stationId = db.KitchenStations.Where(x => x.OutletId == outletSeedId).Select(x => x.KitchenStationId).FirstOrDefault();
                if (stationId > 0)
                {
                    var kot = new KotHeader
                    {
                        OutletId = outletSeedId,
                        KotNo = "KOT00001",
                        KotDate = DateTime.UtcNow,
                        BusinessDate = bizDate,
                        BillId = paidBill.BillId,
                        KitchenStationId = stationId,
                        KotEventType = "New",
                        Status = "Ready"
                    };
                    db.KotHeaders.Add(kot);
                    await db.SaveChangesAsync();

                    db.KotItems.AddRange(
                        new KotItem { KotHeaderId = kot.KotHeaderId, ItemId = seedItems[0].ItemId, ItemNameSnapshot = seedItems[0].ItemName, Qty = 1 },
                        new KotItem { KotHeaderId = kot.KotHeaderId, ItemId = seedItems[1].ItemId, ItemNameSnapshot = seedItems[1].ItemName, Qty = 1 }
                    );
                }
            }

            if (!db.DayCloseReports.Any(x => x.OutletId == outletSeedId))
            {
                db.DayCloseReports.Add(new DayCloseReport
                {
                    OutletId = outletSeedId,
                    BusinessDate = bizDate.AddDays(-1),
                    OpenedAtUtc = DateTime.UtcNow.AddHours(-12),
                    ClosedAtUtc = DateTime.UtcNow.AddHours(-1),
                    ClosedBy = 1,
                    OpeningCash = 1500m,
                    ClosingCash = 2400m,
                    TotalSales = 5200m,
                    TotalTax = 260m,
                    CashOverShort = 20m,
                    IsLocked = true
                });
            }

            if (!db.PaymentCallbackEvents.Any(x => x.Provider == "Razorpay" && x.EventId == $"seed-cb-{outletSeedId}"))
            {
                var payment = db.Payments
                    .Join(db.Bills, p => p.BillId, b => b.BillId, (p, b) => new { p, b })
                    .Where(x => x.b.OutletId == outletSeedId)
                    .Select(x => x.p)
                    .FirstOrDefault();
                db.PaymentCallbackEvents.Add(new PaymentCallbackEvent
                {
                    Provider = "Razorpay",
                    EventId = $"seed-cb-{outletSeedId}",
                    IsValid = true,
                    ProcessingStatus = "Settled",
                    ProcessedAtUtc = DateTime.UtcNow,
                    MatchedPaymentId = payment?.PaymentId,
                    MatchedBillId = payment?.BillId
                });
            }

            if (!db.ReprintLogs.Any(x => x.OutletId == outletSeedId))
            {
                var docId = db.Bills.Where(x => x.OutletId == outletSeedId).Select(x => x.BillId).FirstOrDefault();
                if (docId > 0)
                {
                    db.ReprintLogs.Add(new ReprintLog
                    {
                        OutletId = outletSeedId,
                        DocumentType = "Bill",
                        DocumentId = docId,
                        ReprintedBy = 1,
                        Reason = "Seeded sample reprint trail"
                    });
                }
            }

            if (!db.AuditLogs.Any(x => x.OutletId == outletSeedId))
            {
                db.AuditLogs.Add(new AuditLog
                {
                    OutletId = outletSeedId,
                    UserId = 1,
                    Action = "SeedInit",
                    EntityType = "Seeder",
                    EntityId = $"OUTLET-{outletSeedId}",
                    OldValuesJson = null,
                    NewValuesJson = "{\"seed\":\"transactional-demo\"}",
                    IpAddress = "127.0.0.1",
                    UserAgent = "Seeder",
                    PreviousHash = null,
                    EntryHash = Guid.NewGuid().ToString("N")
                });
            }

            await db.SaveChangesAsync();
        }
    }
}

