using Microsoft.AspNetCore.Identity;
using Entities.Configuration;
using Entities.Enums;
using Entities.Inventory;
using Entities.Kitchen;
using Entities.Masters;
using Data.Persistence;

namespace Data.Seeding;

public static class DbSeeder
{
    public static async Task SeedAsync(
        AppDbContext db,
        UserManager<IdentityUser<int>> userManager,
        RoleManager<IdentityRole<int>> roleManager)
    {
        var roles = new[] { "Admin", "Manager", "Cashier", "Captain", "Kitchen", "StockManager", "Accountant" };
        foreach (var role in roles)
        {
            if (!await roleManager.RoleExistsAsync(role))
            {
                await roleManager.CreateAsync(new IdentityRole<int>(role));
            }
        }

        if (!db.TaxConfigurations.Any())
        {
            db.TaxConfigurations.Add(new TaxConfiguration
            {
                ScenarioType = "Standalone",
                TotalGstPercent = 5m,
                CgstPercent = 2.5m,
                SgstPercent = 2.5m,
                IgstPercent = 0m,
                IsItcAllowed = false,
                EffectiveFrom = new DateTime(2025, 9, 22)
            });
        }

        if (!db.NumberSeries.Any())
        {
            db.NumberSeries.AddRange(
                new NumberSeries { SeriesKey = NumberSeriesKey.Bill, Prefix = "TI", NumberLength = 6 },
                new NumberSeries { SeriesKey = NumberSeriesKey.Quote, Prefix = "QT", NumberLength = 5 },
                new NumberSeries { SeriesKey = NumberSeriesKey.KOT, Prefix = "KOT", NumberLength = 5 });
        }

        if (!db.RestaurantSettings.Any())
        {
            db.RestaurantSettings.AddRange(
                new RestaurantSetting { SettingKey = "RestaurantName", SettingValue = "Restaurant" },
                new RestaurantSetting { SettingKey = "FssaiNumber", SettingValue = "12345678901234" },
                new RestaurantSetting { SettingKey = "ServiceChargeDefault", SettingValue = "0" },
                new RestaurantSetting { SettingKey = "ManagerPin", SettingValue = "9876" },
                new RestaurantSetting { SettingKey = "BillTemplateName", SettingValue = "Classic GST A4" },
                new RestaurantSetting { SettingKey = "BillTemplateHeader", SettingValue = "Thank you for dining with us" },
                new RestaurantSetting { SettingKey = "BillTemplateFooter", SettingValue = "Visit Again | GST invoice generated by system" });
        }

        if (!db.Categories.Any())
        {
            db.Categories.AddRange(
                new Category { CategoryName = "Starters", SortOrder = 1, IsActive = true },
                new Category { CategoryName = "Main Course", SortOrder = 2, IsActive = true },
                new Category { CategoryName = "Breads", SortOrder = 3, IsActive = true },
                new Category { CategoryName = "Desserts", SortOrder = 4, IsActive = true },
                new Category { CategoryName = "Beverages", SortOrder = 5, IsActive = true });
        }

        if (!db.Units.Any())
        {
            db.Units.AddRange(
                new Unit { UnitName = "Nos", UnitCode = "NOS" },
                new Unit { UnitName = "Kg", UnitCode = "KG" },
                new Unit { UnitName = "Litre", UnitCode = "LTR" });
        }

        if (!db.DiningTables.Any())
        {
            db.DiningTables.AddRange(
                new DiningTables { TableName = "Ground-1", Area = "Ground", Capacity = 4 },
                new DiningTables { TableName = "Ground-2", Area = "Ground", Capacity = 6 });
        }

        if (!db.KitchenStations.Any())
        {
            db.KitchenStations.AddRange(
                new KitchenStation { StationName = "Main Kitchen", SortOrder = 1 },
                new KitchenStation { StationName = "Beverage", SortOrder = 2 });
        }

        await db.SaveChangesAsync();

        if (!db.Items.Any())
        {
            var categories = db.Categories.ToDictionary(x => x.CategoryName, x => x.CategoryId);
            db.Items.AddRange(
                new Item { CategoryId = categories["Starters"], ItemCode = "STR001", ItemName = "Paneer Tikka", SalePrice = 260m, GstPercent = 5m, TaxType = TaxType.GST },
                new Item { CategoryId = categories["Main Course"], ItemCode = "MNC001", ItemName = "Veg Biryani", SalePrice = 220m, GstPercent = 5m, TaxType = TaxType.GST },
                new Item { CategoryId = categories["Breads"], ItemCode = "BRD001", ItemName = "Butter Naan", SalePrice = 45m, GstPercent = 5m, TaxType = TaxType.GST });
        }

        if (!db.Groceries.Any())
        {
            db.Groceries.AddRange(
                new Grocery { GroceryName = "Milk", IsActive = true },
                new Grocery { GroceryName = "Rice", IsActive = true },
                new Grocery { GroceryName = "Cooking Oil", IsActive = true });
        }

        await db.SaveChangesAsync();

        if (!db.GroceryStockItems.Any())
        {
            var groceries = db.Groceries.ToList();
            foreach (var grocery in groceries)
            {
                db.GroceryStockItems.Add(new GroceryStockItem
                {
                    GroceryId = grocery.GroceryId,
                    CurrentQty = 0m,
                    ReorderLevel = 0m,
                    IsActive = true
                });
            }
        }

        await db.SaveChangesAsync();

        var adminUser = await userManager.FindByNameAsync("Admin")
            ?? await userManager.FindByEmailAsync("admin@restaurant.local");
        if (adminUser is null)
        {
            adminUser = new IdentityUser<int>
            {
                UserName = "Admin",
                Email = "admin@restaurant.local",
                EmailConfirmed = true
            };
            var createResult = await userManager.CreateAsync(adminUser, "Admin@123");
            if (!createResult.Succeeded)
            {
                throw new InvalidOperationException($"Failed to create default admin user: {string.Join(", ", createResult.Errors.Select(x => x.Description))}");
            }
        }

        if (!await userManager.IsInRoleAsync(adminUser, "Admin"))
        {
            await userManager.AddToRoleAsync(adminUser, "Admin");
        }
    }
}
