using Microsoft.AspNetCore.Identity;
using Entities.Configuration;
using Entities.Enums;
using Entities.Inventory;
using Entities.Kitchen;
using Entities.Masters;
using Data.Persistence;

namespace Data.Seeding;

public static class DbSeeder
{
    public static async Task SeedAsync(
        AppDbContext db,
        UserManager<IdentityUser<int>> userManager,
        RoleManager<IdentityRole<int>> roleManager)
    {
        var roles = new[] { "Admin", "Manager", "Cashier", "Captain", "Kitchen", "StockManager", "Accountant" };
        foreach (var role in roles)
        {
            if (!await roleManager.RoleExistsAsync(role))
            {
                await roleManager.CreateAsync(new IdentityRole<int>(role));
            }
        }

        if (!db.TaxConfigurations.Any())
        {
            db.TaxConfigurations.Add(new TaxConfiguration
            {
                ScenarioType = "Standalone",
                TotalGstPercent = 5m,
                CgstPercent = 2.5m,
                SgstPercent = 2.5m,
                IgstPercent = 0m,
                IsItcAllowed = false,
                EffectiveFrom = new DateTime(2025, 9, 22)
            });
        }

        if (!db.NumberSeries.Any())
        {
            db.NumberSeries.AddRange(
                new NumberSeries { SeriesKey = NumberSeriesKey.Bill, Prefix = "TI", NumberLength = 6 },
                new NumberSeries { SeriesKey = NumberSeriesKey.Quote, Prefix = "QT", NumberLength = 5 },
                new NumberSeries { SeriesKey = NumberSeriesKey.KOT, Prefix = "KOT", NumberLength = 5 });
        }

        if (!db.RestaurantSettings.Any())
        {
            db.RestaurantSettings.AddRange(
                new RestaurantSetting { SettingKey = "RestaurantName", SettingValue = "Restaurant" },
                new RestaurantSetting { SettingKey = "RestaurantAddress", SettingValue = "Main Road, City Center" },
                new RestaurantSetting { SettingKey = "RestaurantPhone", SettingValue = "+91-99999-12345" },
                new RestaurantSetting { SettingKey = "FssaiNumber", SettingValue = "12345678901234" },
                new RestaurantSetting { SettingKey = "ServiceChargeDefault", SettingValue = "0" },
                new RestaurantSetting { SettingKey = "ManagerPin", SettingValue = "9876" },
                new RestaurantSetting { SettingKey = "ClosingTime", SettingValue = "02:00" },
                new RestaurantSetting { SettingKey = "BillTemplateName", SettingValue = "Classic GST A4" },
                new RestaurantSetting { SettingKey = "BillTemplateHeader", SettingValue = "Thank you for dining with us" },
                new RestaurantSetting { SettingKey = "BillTemplateFooter", SettingValue = "Visit Again | GST invoice generated by system" });
        }

        if (!db.Categories.Any())
        {
            db.Categories.AddRange(
                new Category { CategoryName = "Starters", SortOrder = 1, IsActive = true },
                new Category { CategoryName = "Main Course", SortOrder = 2, IsActive = true },
                new Category { CategoryName = "Breads", SortOrder = 3, IsActive = true },
                new Category { CategoryName = "Desserts", SortOrder = 4, IsActive = true },
                new Category { CategoryName = "Beverages", SortOrder = 5, IsActive = true },
                new Category { CategoryName = "Rice & Biryani", SortOrder = 6, IsActive = true },
                new Category { CategoryName = "Soups", SortOrder = 7, IsActive = true });
        }

        if (!db.Units.Any())
        {
            db.Units.AddRange(
                new Unit { UnitName = "Nos", UnitCode = "NOS" },
                new Unit { UnitName = "Kg", UnitCode = "KG" },
                new Unit { UnitName = "Litre", UnitCode = "LTR" },
                new Unit { UnitName = "Gram", UnitCode = "G" },
                new Unit { UnitName = "Millilitre", UnitCode = "ML" },
                new Unit { UnitName = "Plate", UnitCode = "PLT" });
        }

        if (!db.DiningTables.Any())
        {
            db.DiningTables.AddRange(
                new DiningTables { TableName = "Ground-1", Area = "Ground", Capacity = 4 },
                new DiningTables { TableName = "Ground-2", Area = "Ground", Capacity = 6 },
                new DiningTables { TableName = "Ground-3", Area = "Ground", Capacity = 4 },
                new DiningTables { TableName = "Family-1", Area = "First Floor", Capacity = 8 },
                new DiningTables { TableName = "Family-2", Area = "First Floor", Capacity = 8 },
                new DiningTables { TableName = "Terrace-1", Area = "Terrace", Capacity = 6 });
        }

        if (!db.KitchenStations.Any())
        {
            db.KitchenStations.AddRange(
                new KitchenStation { StationName = "Main Kitchen", SortOrder = 1 },
                new KitchenStation { StationName = "Beverage", SortOrder = 2 },
                new KitchenStation { StationName = "Tandoor", SortOrder = 3 },
                new KitchenStation { StationName = "Dessert Counter", SortOrder = 4 });
        }

        await db.SaveChangesAsync();

        if (!db.Items.Any())
        {
            var categories = db.Categories.ToDictionary(x => x.CategoryName, x => x.CategoryId);
            db.Items.AddRange(
                new Item { CategoryId = categories["Starters"], ItemCode = "STR001", ItemName = "Paneer Tikka", SalePrice = 260m, GstPercent = 5m, IsStock = false, TaxType = TaxType.GST },
                new Item { CategoryId = categories["Starters"], ItemCode = "STR002", ItemName = "Hara Bhara Kebab", SalePrice = 240m, GstPercent = 5m, IsStock = false, TaxType = TaxType.GST },
                new Item { CategoryId = categories["Starters"], ItemCode = "STR003", ItemName = "Corn Tikki", SalePrice = 175m, GstPercent = 5m, IsStock = false, TaxType = TaxType.GST },
                new Item { CategoryId = categories["Starters"], ItemCode = "STR004", ItemName = "Samosa", SalePrice = 35m, GstPercent = 5m, IsStock = true, TaxType = TaxType.GST },
                new Item { CategoryId = categories["Starters"], ItemCode = "STR005", ItemName = "Kachori", SalePrice = 40m, GstPercent = 5m, IsStock = true, TaxType = TaxType.GST },
                new Item { CategoryId = categories["Starters"], ItemCode = "STR006", ItemName = "Dahi Kachori", SalePrice = 65m, GstPercent = 5m, IsStock = true, TaxType = TaxType.GST },
                new Item { CategoryId = categories["Main Course"], ItemCode = "MNC002", ItemName = "Paneer Butter Masala", SalePrice = 280m, GstPercent = 5m, IsStock = false, TaxType = TaxType.GST },
                new Item { CategoryId = categories["Main Course"], ItemCode = "MNC003", ItemName = "Dal Tadka", SalePrice = 160m, GstPercent = 5m, IsStock = false, TaxType = TaxType.GST },
                new Item { CategoryId = categories["Main Course"], ItemCode = "MNC004", ItemName = "Mix Veg Curry", SalePrice = 210m, GstPercent = 5m, IsStock = false, TaxType = TaxType.GST },
                new Item { CategoryId = categories["Main Course"], ItemCode = "MNC001", ItemName = "Veg Biryani", SalePrice = 220m, GstPercent = 5m, IsStock = false, TaxType = TaxType.GST },
                new Item { CategoryId = categories["Breads"], ItemCode = "BRD001", ItemName = "Butter Naan", SalePrice = 45m, GstPercent = 5m, IsStock = false, TaxType = TaxType.GST },
                new Item { CategoryId = categories["Breads"], ItemCode = "BRD002", ItemName = "Tandoori Roti", SalePrice = 30m, GstPercent = 5m, IsStock = false, TaxType = TaxType.GST },
                new Item { CategoryId = categories["Breads"], ItemCode = "BRD003", ItemName = "Garlic Naan", SalePrice = 60m, GstPercent = 5m, IsStock = false, TaxType = TaxType.GST },
                new Item { CategoryId = categories["Desserts"], ItemCode = "DST001", ItemName = "Gulab Jamun", SalePrice = 90m, GstPercent = 5m, IsStock = true, TaxType = TaxType.GST },
                new Item { CategoryId = categories["Desserts"], ItemCode = "DST002", ItemName = "Chocolate Brownie", SalePrice = 160m, GstPercent = 5m, IsStock = true, TaxType = TaxType.GST },
                new Item { CategoryId = categories["Desserts"], ItemCode = "DST003", ItemName = "Ladoo", SalePrice = 120m, GstPercent = 5m, IsStock = true, TaxType = TaxType.GST },
                new Item { CategoryId = categories["Desserts"], ItemCode = "DST004", ItemName = "Kaju Barfi", SalePrice = 220m, GstPercent = 5m, IsStock = true, TaxType = TaxType.GST },
                new Item { CategoryId = categories["Desserts"], ItemCode = "DST005", ItemName = "Sweet Lassi", SalePrice = 80m, GstPercent = 5m, IsStock = true, TaxType = TaxType.GST },
                new Item { CategoryId = categories["Desserts"], ItemCode = "DST006", ItemName = "Rabdi", SalePrice = 150m, GstPercent = 5m, IsStock = true, TaxType = TaxType.GST },
                new Item { CategoryId = categories["Desserts"], ItemCode = "DST007", ItemName = "Rasmalai", SalePrice = 170m, GstPercent = 5m, IsStock = true, TaxType = TaxType.GST },
                new Item { CategoryId = categories["Beverages"], ItemCode = "BEV001", ItemName = "Masala Chai", SalePrice = 35m, GstPercent = 5m, IsStock = false, TaxType = TaxType.GST },
                new Item { CategoryId = categories["Beverages"], ItemCode = "BEV002", ItemName = "Cold Coffee", SalePrice = 120m, GstPercent = 5m, IsStock = false, TaxType = TaxType.GST },
                new Item { CategoryId = categories["Rice & Biryani"], ItemCode = "RCB001", ItemName = "Jeera Rice", SalePrice = 140m, GstPercent = 5m, IsStock = false, TaxType = TaxType.GST },
                new Item { CategoryId = categories["Rice & Biryani"], ItemCode = "RCB002", ItemName = "Steam Rice", SalePrice = 110m, GstPercent = 5m, IsStock = false, TaxType = TaxType.GST },
                new Item { CategoryId = categories["Soups"], ItemCode = "SOP001", ItemName = "Tomato Soup", SalePrice = 95m, GstPercent = 5m, IsStock = false, TaxType = TaxType.GST },
                new Item { CategoryId = categories["Soups"], ItemCode = "SOP002", ItemName = "Sweet Corn Soup", SalePrice = 110m, GstPercent = 5m, IsStock = false, TaxType = TaxType.GST });
        }

        // Ensure stock-tracked seed items exist even for already-initialized databases.
        {
            var categories = db.Categories.ToDictionary(x => x.CategoryName, x => x.CategoryId);
            var dessertCategoryId = categories["Desserts"];
            var startersCategoryId = categories["Starters"];
            var existingCodes = db.Items
                .Where(x => !x.IsDeleted)
                .Select(x => x.ItemCode)
                .ToHashSet(StringComparer.OrdinalIgnoreCase);

            var requiredStockItems = new[]
            {
                new { CategoryId = dessertCategoryId, Code = "DST001", Name = "Gulab Jamun", Sale = 90m },
                new { CategoryId = dessertCategoryId, Code = "DST002", Name = "Chocolate Brownie", Sale = 160m },
                new { CategoryId = dessertCategoryId, Code = "DST003", Name = "Ladoo", Sale = 120m },
                new { CategoryId = dessertCategoryId, Code = "DST004", Name = "Kaju Barfi", Sale = 220m },
                new { CategoryId = dessertCategoryId, Code = "DST005", Name = "Sweet Lassi", Sale = 80m },
                new { CategoryId = dessertCategoryId, Code = "DST006", Name = "Rabdi", Sale = 150m },
                new { CategoryId = dessertCategoryId, Code = "DST007", Name = "Rasmalai", Sale = 170m },
                new { CategoryId = startersCategoryId, Code = "STR004", Name = "Samosa", Sale = 35m },
                new { CategoryId = startersCategoryId, Code = "STR005", Name = "Kachori", Sale = 40m },
                new { CategoryId = startersCategoryId, Code = "STR006", Name = "Dahi Kachori", Sale = 65m }
            };

            var missingStockItems = requiredStockItems
                .Where(x => !existingCodes.Contains(x.Code))
                .Select(x => new Item
                {
                    CategoryId = x.CategoryId,
                    ItemCode = x.Code,
                    ItemName = x.Name,
                    SalePrice = x.Sale,
                    GstPercent = 5m,
                    IsStock = true,
                    TaxType = TaxType.GST
                })
                .ToList();

            if (missingStockItems.Count > 0)
            {
                db.Items.AddRange(missingStockItems);
            }

            // Keep requested units consistent for existing dessert items.
            var ladoo = db.Items.FirstOrDefault(x => !x.IsDeleted && x.ItemCode == "DST003");
            if (ladoo is not null)
            {
                ladoo.IsStock = true;
            }
            var kajuBarfi = db.Items.FirstOrDefault(x => !x.IsDeleted && x.ItemCode == "DST004");
            if (kajuBarfi is not null)
            {
                kajuBarfi.IsStock = true;
            }
            var samosa = db.Items.FirstOrDefault(x => !x.IsDeleted && x.ItemCode == "STR004");
            if (samosa is not null)
            {
                samosa.IsStock = true;
            }
            var kachori = db.Items.FirstOrDefault(x => !x.IsDeleted && x.ItemCode == "STR005");
            if (kachori is not null)
            {
                kachori.IsStock = true;
            }
            var dahiKachori = db.Items.FirstOrDefault(x => !x.IsDeleted && x.ItemCode == "STR006");
            if (dahiKachori is not null)
            {
                dahiKachori.IsStock = true;
            }
        }

        await db.SaveChangesAsync();

        {
            var today = DateOnly.FromDateTime(DateTime.UtcNow.Date);
            var units = db.Units.ToDictionary(x => x.UnitCode, x => x.UnitId);
            var stockTrackedItems = db.Items
                .Where(x => !x.IsDeleted && x.IsStock)
                .ToList();

            foreach (var item in stockTrackedItems)
            {
                var hasIn = db.ItemStocks.Any(x => !x.IsDeleted && x.ItemId == item.ItemId && x.Type == "in");
                if (!hasIn)
                {
                    var unitId = ResolveStockUnitId(item.ItemCode, units);
                    db.ItemStocks.Add(new ItemStock
                    {
                        ItemId = item.ItemId,
                        UnitId = unitId,
                        CurrentQty = 30m,
                        ReorderLevel = 10m,
                        Type = "in",
                        StockDate = today,
                        IsActive = true,
                        IsDeleted = false
                    });
                }

                var hasOut = db.ItemStocks.Any(x => !x.IsDeleted && x.ItemId == item.ItemId && x.Type == "out");
                if (!hasOut)
                {
                    var unitId = ResolveStockUnitId(item.ItemCode, units);
                    db.ItemStocks.Add(new ItemStock
                    {
                        ItemId = item.ItemId,
                        UnitId = unitId,
                        CurrentQty = 2m,
                        ReorderLevel = 10m,
                        Type = "out",
                        StockDate = today,
                        IsActive = true,
                        IsDeleted = false
                    });
                }
            }

            await db.SaveChangesAsync();
        }

        var adminUser = await userManager.FindByNameAsync("Admin")
            ?? await userManager.FindByEmailAsync("admin@restaurant.local");
        if (adminUser is null)
        {
            adminUser = new IdentityUser<int>
            {
                UserName = "Admin",
                Email = "admin@restaurant.local",
                EmailConfirmed = true
            };
            var createResult = await userManager.CreateAsync(adminUser, "Admin@123");
            if (!createResult.Succeeded)
            {
                throw new InvalidOperationException($"Failed to create default admin user: {string.Join(", ", createResult.Errors.Select(x => x.Description))}");
            }
        }

        if (!await userManager.IsInRoleAsync(adminUser, "Admin"))
        {
            await userManager.AddToRoleAsync(adminUser, "Admin");
        }

        var defaultUsers = new (string UserName, string Email, string Password, string Role)[]
        {
            ("Manager", "manager@restaurant.local", "Manager@123", "Manager"),
            ("Cashier", "cashier@restaurant.local", "Cashier@123", "Cashier"),
            ("Captain", "captain@restaurant.local", "Captain@123", "Captain"),
            ("Kitchen", "kitchen@restaurant.local", "Kitchen@123", "Kitchen")
        };

        foreach (var defaultUser in defaultUsers)
        {
            var user = await userManager.FindByNameAsync(defaultUser.UserName)
                ?? await userManager.FindByEmailAsync(defaultUser.Email);
            if (user is null)
            {
                user = new IdentityUser<int>
                {
                    UserName = defaultUser.UserName,
                    Email = defaultUser.Email,
                    EmailConfirmed = true
                };
                var createResult = await userManager.CreateAsync(user, defaultUser.Password);
                if (!createResult.Succeeded)
                {
                    throw new InvalidOperationException($"Failed to create default user '{defaultUser.UserName}': {string.Join(", ", createResult.Errors.Select(x => x.Description))}");
                }
            }

            if (!await userManager.IsInRoleAsync(user, defaultUser.Role))
            {
                await userManager.AddToRoleAsync(user, defaultUser.Role);
            }
        }
    }

    private static int? ResolveStockUnitId(string itemCode, IReadOnlyDictionary<string, int> units)
    {
        if (itemCode is "DST003" or "DST004")
        {
            return units.TryGetValue("KG", out var kgUnitId) ? kgUnitId : null;
        }

        if (itemCode is "STR004" or "STR005" or "STR006")
        {
            return units.TryGetValue("NOS", out var nosUnitId) ? nosUnitId : null;
        }

        return null;
    }
}
